[project]
name = "agent-server"
version = "0.1.0"
description = "Listify AI Agent Server"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.135.1",
    "pydantic>=2.12.5",
    "pydantic-ai-slim[ag-ui]>=1.68.0",
    "pydantic-ai[anthropic]>=1.68.0",
    "python-dotenv>=1.2.2",
    "uvicorn>=0.41.0",
]
